// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//
// BeaconControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class BeaconControllerAPI {
    /**
     Create a beacon
     
     - parameter order: (body) order 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createUsingPOST(order: ManufacturerOrder, completion: @escaping ((_ data: [Beacon]?,_ error: Error?) -> Void)) {
        createUsingPOSTWithRequestBuilder(order: order).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Create a beacon
     - POST /v1/admin/beacons/createByOrder
     - API Key:
       - type: apiKey Authorization 
       - name: JWT
     - examples: [{contentType=application/json, example=[ {
  "minor" : 7,
  "iBeacon" : true,
  "locationDescription" : "locationDescription",
  "description" : "description",
  "locationType" : "OUTDOOR",
  "eddystoneUid" : true,
  "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "manufacturer" : "KONTAKT_IO",
  "eddystoneTlm" : true,
  "internalName" : "internalName",
  "txPower" : 7,
  "instanceId" : "instanceId",
  "major" : 2,
  "eddystoneEid" : true,
  "id" : "id",
  "lat" : 5.962134,
  "batteryLevel" : 0,
  "eddystoneEtlm" : true,
  "lng" : 5.637377,
  "pendingConfiguration" : {
    "eddystoneEtlm" : true,
    "minor" : 2,
    "iBeacon" : true,
    "eddystoneUid" : true,
    "eddystoneUrl" : true,
    "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "url" : "url",
    "eddystoneTlm" : true,
    "txPower" : 4,
    "instanceId" : "instanceId",
    "major" : 3,
    "namespace" : "namespace",
    "eddystoneEid" : true,
    "interval" : 9,
    "telemetry" : true
  },
  "manufacturerId" : "manufacturerId",
  "eddystoneUrl" : true,
  "url" : "url",
  "lastSeen" : 1,
  "name" : "name",
  "namespace" : "namespace",
  "interval" : 6,
  "telemetry" : true,
  "status" : "OK"
}, {
  "minor" : 7,
  "iBeacon" : true,
  "locationDescription" : "locationDescription",
  "description" : "description",
  "locationType" : "OUTDOOR",
  "eddystoneUid" : true,
  "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "manufacturer" : "KONTAKT_IO",
  "eddystoneTlm" : true,
  "internalName" : "internalName",
  "txPower" : 7,
  "instanceId" : "instanceId",
  "major" : 2,
  "eddystoneEid" : true,
  "id" : "id",
  "lat" : 5.962134,
  "batteryLevel" : 0,
  "eddystoneEtlm" : true,
  "lng" : 5.637377,
  "pendingConfiguration" : {
    "eddystoneEtlm" : true,
    "minor" : 2,
    "iBeacon" : true,
    "eddystoneUid" : true,
    "eddystoneUrl" : true,
    "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "url" : "url",
    "eddystoneTlm" : true,
    "txPower" : 4,
    "instanceId" : "instanceId",
    "major" : 3,
    "namespace" : "namespace",
    "eddystoneEid" : true,
    "interval" : 9,
    "telemetry" : true
  },
  "manufacturerId" : "manufacturerId",
  "eddystoneUrl" : true,
  "url" : "url",
  "lastSeen" : 1,
  "name" : "name",
  "namespace" : "namespace",
  "interval" : 6,
  "telemetry" : true,
  "status" : "OK"
} ]}]
     
     - parameter order: (body) order 

     - returns: RequestBuilder<[Beacon]> 
     */
    open class func createUsingPOSTWithRequestBuilder(order: ManufacturerOrder) -> RequestBuilder<[Beacon]> {
        let path = "/v1/admin/beacons/createByOrder"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: order)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[Beacon]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     View a list of available beacons
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getListUsingGET(completion: @escaping ((_ data: [Beacon]?,_ error: Error?) -> Void)) {
        getListUsingGETWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     View a list of available beacons
     - GET /v1/admin/beacons
     - API Key:
       - type: apiKey Authorization 
       - name: JWT
     - examples: [{contentType=application/json, example=[ {
  "minor" : 7,
  "iBeacon" : true,
  "locationDescription" : "locationDescription",
  "description" : "description",
  "locationType" : "OUTDOOR",
  "eddystoneUid" : true,
  "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "manufacturer" : "KONTAKT_IO",
  "eddystoneTlm" : true,
  "internalName" : "internalName",
  "txPower" : 7,
  "instanceId" : "instanceId",
  "major" : 2,
  "eddystoneEid" : true,
  "id" : "id",
  "lat" : 5.962134,
  "batteryLevel" : 0,
  "eddystoneEtlm" : true,
  "lng" : 5.637377,
  "pendingConfiguration" : {
    "eddystoneEtlm" : true,
    "minor" : 2,
    "iBeacon" : true,
    "eddystoneUid" : true,
    "eddystoneUrl" : true,
    "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "url" : "url",
    "eddystoneTlm" : true,
    "txPower" : 4,
    "instanceId" : "instanceId",
    "major" : 3,
    "namespace" : "namespace",
    "eddystoneEid" : true,
    "interval" : 9,
    "telemetry" : true
  },
  "manufacturerId" : "manufacturerId",
  "eddystoneUrl" : true,
  "url" : "url",
  "lastSeen" : 1,
  "name" : "name",
  "namespace" : "namespace",
  "interval" : 6,
  "telemetry" : true,
  "status" : "OK"
}, {
  "minor" : 7,
  "iBeacon" : true,
  "locationDescription" : "locationDescription",
  "description" : "description",
  "locationType" : "OUTDOOR",
  "eddystoneUid" : true,
  "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "manufacturer" : "KONTAKT_IO",
  "eddystoneTlm" : true,
  "internalName" : "internalName",
  "txPower" : 7,
  "instanceId" : "instanceId",
  "major" : 2,
  "eddystoneEid" : true,
  "id" : "id",
  "lat" : 5.962134,
  "batteryLevel" : 0,
  "eddystoneEtlm" : true,
  "lng" : 5.637377,
  "pendingConfiguration" : {
    "eddystoneEtlm" : true,
    "minor" : 2,
    "iBeacon" : true,
    "eddystoneUid" : true,
    "eddystoneUrl" : true,
    "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "url" : "url",
    "eddystoneTlm" : true,
    "txPower" : 4,
    "instanceId" : "instanceId",
    "major" : 3,
    "namespace" : "namespace",
    "eddystoneEid" : true,
    "interval" : 9,
    "telemetry" : true
  },
  "manufacturerId" : "manufacturerId",
  "eddystoneUrl" : true,
  "url" : "url",
  "lastSeen" : 1,
  "name" : "name",
  "namespace" : "namespace",
  "interval" : 6,
  "telemetry" : true,
  "status" : "OK"
} ]}]

     - returns: RequestBuilder<[Beacon]> 
     */
    open class func getListUsingGETWithRequestBuilder() -> RequestBuilder<[Beacon]> {
        let path = "/v1/admin/beacons"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[Beacon]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search a beacon with an ID
     
     - parameter id: (path) id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getUsingGET(id: String, completion: @escaping ((_ data: Beacon?,_ error: Error?) -> Void)) {
        getUsingGETWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Search a beacon with an ID
     - GET /v1/admin/beacons/{id}
     - API Key:
       - type: apiKey Authorization 
       - name: JWT
     - examples: [{contentType=application/json, example={
  "minor" : 7,
  "iBeacon" : true,
  "locationDescription" : "locationDescription",
  "description" : "description",
  "locationType" : "OUTDOOR",
  "eddystoneUid" : true,
  "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "manufacturer" : "KONTAKT_IO",
  "eddystoneTlm" : true,
  "internalName" : "internalName",
  "txPower" : 7,
  "instanceId" : "instanceId",
  "major" : 2,
  "eddystoneEid" : true,
  "id" : "id",
  "lat" : 5.962134,
  "batteryLevel" : 0,
  "eddystoneEtlm" : true,
  "lng" : 5.637377,
  "pendingConfiguration" : {
    "eddystoneEtlm" : true,
    "minor" : 2,
    "iBeacon" : true,
    "eddystoneUid" : true,
    "eddystoneUrl" : true,
    "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "url" : "url",
    "eddystoneTlm" : true,
    "txPower" : 4,
    "instanceId" : "instanceId",
    "major" : 3,
    "namespace" : "namespace",
    "eddystoneEid" : true,
    "interval" : 9,
    "telemetry" : true
  },
  "manufacturerId" : "manufacturerId",
  "eddystoneUrl" : true,
  "url" : "url",
  "lastSeen" : 1,
  "name" : "name",
  "namespace" : "namespace",
  "interval" : 6,
  "telemetry" : true,
  "status" : "OK"
}}]
     
     - parameter id: (path) id 

     - returns: RequestBuilder<Beacon> 
     */
    open class func getUsingGETWithRequestBuilder(id: String) -> RequestBuilder<Beacon> {
        var path = "/v1/admin/beacons/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Beacon>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update a beacon
     
     - parameter beaconUpdate: (body) beaconUpdate 
     - parameter id: (path) id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateUsingPATCH(beaconUpdate: BeaconUpdate, id: String, completion: @escaping ((_ data: Beacon?,_ error: Error?) -> Void)) {
        updateUsingPATCHWithRequestBuilder(beaconUpdate: beaconUpdate, id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Update a beacon
     - PATCH /v1/admin/beacons/{id}
     - API Key:
       - type: apiKey Authorization 
       - name: JWT
     - examples: [{contentType=application/json, example={
  "minor" : 7,
  "iBeacon" : true,
  "locationDescription" : "locationDescription",
  "description" : "description",
  "locationType" : "OUTDOOR",
  "eddystoneUid" : true,
  "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "manufacturer" : "KONTAKT_IO",
  "eddystoneTlm" : true,
  "internalName" : "internalName",
  "txPower" : 7,
  "instanceId" : "instanceId",
  "major" : 2,
  "eddystoneEid" : true,
  "id" : "id",
  "lat" : 5.962134,
  "batteryLevel" : 0,
  "eddystoneEtlm" : true,
  "lng" : 5.637377,
  "pendingConfiguration" : {
    "eddystoneEtlm" : true,
    "minor" : 2,
    "iBeacon" : true,
    "eddystoneUid" : true,
    "eddystoneUrl" : true,
    "uuid" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "url" : "url",
    "eddystoneTlm" : true,
    "txPower" : 4,
    "instanceId" : "instanceId",
    "major" : 3,
    "namespace" : "namespace",
    "eddystoneEid" : true,
    "interval" : 9,
    "telemetry" : true
  },
  "manufacturerId" : "manufacturerId",
  "eddystoneUrl" : true,
  "url" : "url",
  "lastSeen" : 1,
  "name" : "name",
  "namespace" : "namespace",
  "interval" : 6,
  "telemetry" : true,
  "status" : "OK"
}}]
     
     - parameter beaconUpdate: (body) beaconUpdate 
     - parameter id: (path) id 

     - returns: RequestBuilder<Beacon> 
     */
    open class func updateUsingPATCHWithRequestBuilder(beaconUpdate: BeaconUpdate, id: String) -> RequestBuilder<Beacon> {
        var path = "/v1/admin/beacons/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: beaconUpdate)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Beacon>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
