default_platform(:ios)

platform :ios do

  desc "Runs all the tests"
  lane :test do
    cocoapods(
        podfile: "./Podfile",
        repo_update: true
    )
    run_tests(
        device: "iPhone 6s",
        scheme: "Beacon SDK iOS",
        xcargs: "-UseModernBuildSystem=NO"
    )
  end
end
