default_platform(:ios)

platform :ios do

  desc "Runs all the tests"
  lane :test do
    cocoapods(
      podfile: "./Podfile",
      repo_update: true
    )
    run_tests(
      project: "Beacon SDK iOS.xcodeproj",
      device: "iPhone 8",
      scheme: "Beacon_SDK_iOSTests",
      xcargs: "-UseModernBuildSystem=NO"
    )
  end
end
