//
// AuthenticationTokenCheck.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AuthenticationTokenCheck: Codable {

    public var token: String?
    public var valid: Bool?


    
    public init(token: String?, valid: Bool?) {
        self.token = token
        self.valid = valid
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(token, forKey: "token")
        try container.encodeIfPresent(valid, forKey: "valid")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        token = try container.decodeIfPresent(String.self, forKey: "token")
        valid = try container.decodeIfPresent(Bool.self, forKey: "valid")
    }
}

