// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//
// AuthenticationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AuthenticationRequest: Codable {

    public var password: String
    public var username: String


    
    public init(password: String, username: String) {
        self.password = password
        self.username = username
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(password, forKey: "password")
        try container.encode(username, forKey: "username")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        password = try container.decode(String.self, forKey: "password")
        username = try container.decode(String.self, forKey: "username")
    }
}

