// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//
// BeaconImage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class BeaconImage: Codable {

    public var fileName: String?
    public var id: Int64?


    
    public init(fileName: String?, id: Int64?) {
        self.fileName = fileName
        self.id = id
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(fileName, forKey: "fileName")
        try container.encodeIfPresent(id, forKey: "id")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        fileName = try container.decodeIfPresent(String.self, forKey: "fileName")
        id = try container.decodeIfPresent(Int64.self, forKey: "id")
    }
}

