// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//
// BeaconOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class BeaconOrder: Codable {

    public var beacons: [BeaconOrderData]?
    public var orderSymbol: String?


    
    public init(beacons: [BeaconOrderData]?, orderSymbol: String?) {
        self.beacons = beacons
        self.orderSymbol = orderSymbol
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(beacons, forKey: "beacons")
        try container.encodeIfPresent(orderSymbol, forKey: "orderSymbol")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        beacons = try container.decodeIfPresent([BeaconOrderData].self, forKey: "beacons")
        orderSymbol = try container.decodeIfPresent(String.self, forKey: "orderSymbol")
    }
}

