//
// PasswordChange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PasswordChange: Codable {

    public var newPassword: String
    public var oldPassword: String


    
    public init(newPassword: String, oldPassword: String) {
        self.newPassword = newPassword
        self.oldPassword = oldPassword
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(newPassword, forKey: "newPassword")
        try container.encode(oldPassword, forKey: "oldPassword")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        newPassword = try container.decode(String.self, forKey: "newPassword")
        oldPassword = try container.decode(String.self, forKey: "oldPassword")
    }
}

