//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class User: Codable {

    public var email: String?
    public var id: Int64?
    public var name: String?
    public var surname: String?
    public var username: String?


    
    public init(email: String?, id: Int64?, name: String?, surname: String?, username: String?) {
        self.email = email
        self.id = id
        self.name = name
        self.surname = surname
        self.username = username
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(email, forKey: "email")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(surname, forKey: "surname")
        try container.encodeIfPresent(username, forKey: "username")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        email = try container.decodeIfPresent(String.self, forKey: "email")
        id = try container.decodeIfPresent(Int64.self, forKey: "id")
        name = try container.decodeIfPresent(String.self, forKey: "name")
        surname = try container.decodeIfPresent(String.self, forKey: "surname")
        username = try container.decodeIfPresent(String.self, forKey: "username")
    }
}

