//
// UserCreation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class UserCreation: Codable {

    public var email: String
    public var name: String
    public var password: String
    public var surname: String
    public var username: String


    
    public init(email: String, name: String, password: String, surname: String, username: String) {
        self.email = email
        self.name = name
        self.password = password
        self.surname = surname
        self.username = username
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(email, forKey: "email")
        try container.encode(name, forKey: "name")
        try container.encode(password, forKey: "password")
        try container.encode(surname, forKey: "surname")
        try container.encode(username, forKey: "username")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        email = try container.decode(String.self, forKey: "email")
        name = try container.decode(String.self, forKey: "name")
        password = try container.decode(String.self, forKey: "password")
        surname = try container.decode(String.self, forKey: "surname")
        username = try container.decode(String.self, forKey: "username")
    }
}

