# version 1.0
name: CI

on: push


jobs:
  build:
    runs-on: macos-11
    
    steps:
      - uses: actions/checkout@v2

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: update
        run: bundle update
      
      - name: test
        run: bundle exec fastlane test
