name: Reuse
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1